fix: constructor expects argument
By try to compilation Poly_J.v, some errors have been occured like below:
> Error: The constructor nil (in type list) expects 1 argument.